//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhachHang
    {
        public tblKhachHang()
        {
            this.tblLichSus = new HashSet<tblLichSu>();
            this.tblNhoms = new HashSet<tblNhom>();
        }
    
        public long MaKhachHang { get; set; }
        public string TenKhachHang { get; set; }
        public string SoDT { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu1 { get; set; }
        public string GhiChu2 { get; set; }
        public string GhiChu3 { get; set; }
        public string GhiChu4 { get; set; }
        public Nullable<double> GiaTri { get; set; }
        public Nullable<int> TrangThai1 { get; set; }
        public Nullable<int> TrangThai2 { get; set; }
        public Nullable<int> TrangThai3 { get; set; }
        public Nullable<int> TrangThai4 { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayUpdate { get; set; }
        public string UserTao { get; set; }
        public string UserUpdate { get; set; }
    
        public virtual ICollection<tblLichSu> tblLichSus { get; set; }
        public virtual ICollection<tblNhom> tblNhoms { get; set; }
    }
}
