//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhom
    {
        public tblNhom()
        {
            this.tblAccounts = new HashSet<tblAccount>();
            this.tblKhachHangs = new HashSet<tblKhachHang>();
        }
    
        public long MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string MoTaoNhom { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayUpdate { get; set; }
        public string UserTao { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<tblAccount> tblAccounts { get; set; }
        public virtual ICollection<tblKhachHang> tblKhachHangs { get; set; }
    }
}
