//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCongTacVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhongBan
    {
        public tblPhongBan()
        {
            this.tblAccounts = new HashSet<tblAccount>();
        }
    
        public long MaPhongBan { get; set; }
        public string TenPhongBan { get; set; }
        public string MoTaPhongBan { get; set; }
        public string GhiChuPhongBan { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayUpdate { get; set; }
        public string UserTao { get; set; }
        public string UserUpdate { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<tblAccount> tblAccounts { get; set; }
    }
}
